Normally, every statement executed requires a round-trip to the database server.
When inserting or updating a large number of records, this can add unacceptable
amounts of latency.  JDBC provides support for batching independent statements via
link:http://docs.oracle.com/javase/8/docs/api/java/sql/Statement.html#executeBatch--[Statement.executeBatch]
as well as a single statement with many varying bound arguments via
link:http://docs.oracle.com/javase/8/docs/api/java/sql/PreparedStatement.html#addBatch--[PreparedStatement.addBatch].

*jdbi* exposes this functionality through the *Batch* and *PreparedBatch* classes.
Their use is straightforward.  To execute many separate statements as a single batch:

[source,java,indent=0]
-------------------------------------------
include::{exampledir}/BatchTest.java[tags=simpleBatch]
-------------------------------------------

If you have a single statement but want to bind many groups of parameters:

[source,java,indent=0]
-------------------------------------------
include::{exampledir}/BatchTest.java[tags=preparedBatch]
-------------------------------------------

We also support SqlObject batch inserts:

[source,java,indent=0]
-------------------------------------------
include::{exampledir}/BatchTest.java[tags=sqlObjectBatch]
-------------------------------------------

== Exception Rewriting

The JDBC SQLException class is very old and predates more modern exception facilities like
Throwable's suppressed exceptions.  When a batch fails, there may be multiple failures to
report, which could not be represented by the base Exception types of the day.

So SQLException has a bespoke
link:http://docs.oracle.com/javase/8/docs/api/java/sql/SQLException.html#getNextException--[getNextException]
chain to represent the causes of a batch failure.  Unfortunately, by default most logging libraries
do not print these exceptions out, pushing their handling into your code.  It is very common
to forget to handle this situation and end up with logs that say nothing other than

-------------------------------------------
java.sql.BatchUpdateException: Batch entry 1 insert into something (id, name) values (0, '') was aborted.  Call getNextException to see the cause.
-------------------------------------------

*jdbi* will attempt to rewrite such nextExceptions into "suppressed exceptions" (new in Java 8) so that your logs are more helpful:

-------------------------------------------
java.sql.BatchUpdateException: Batch entry 1 insert into something (id, name) values (0, 'Keith') was aborted.  Call getNextException to see the cause.
Suppressed: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "something_pkey"
  Detail: Key (id)=(0) already exists.
-------------------------------------------
