*JDBI* is a thin wrapper around the Java database
API, JDBC.  It provides helpful abstractions around
accessing your database tables in a way that respects
the relational model.

Unlike an ORM, *jdbi* does not pretend to seamlessly
convert your Java object model into the relational
model -- instead, it provides easy mapping between
SQL _you_ write and simple tabular data structures.

[source,java,indent=0]
-------------------------------------------
include::{exampledir}/HelloWorldTest.java[tags=frontPage]
-------------------------------------------

*jdbi* is easy to include in your Java project - with an
link:https://groups.google.com/group/jdbi[Apache 2.0] license,
few external dependencies, and JARs distributed through
link:http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.jdbi%22[Maven Central],
you can just include the relevant artifacts in your POM:

[source,xml,subs="attributes,specialchars"]
-------------------------------------------
<dependency>
  <groupId>org.jdbi</groupId>
  <artifactId>jdbi3</artifactId>
  <version>{project_version}</version>
</dependency>
-------------------------------------------

*jdbi3* is an update which sports a cleaned up API,
a stronger resource ownership model, and leverages
the power of new Java 8 features.

WARNING: *jdbi3* is currently in beta. While we are reasonably confident in its
quality, we recommend thoroughly testing your code with JDBI 3 before using it in
a production environment. http://www.jdbi.org[jdbi2] is still the stable release.
