*JDBI* is a Java library providing convenient, idiomatic access to relational
data.

JDBI is built on top of JDBC. If your database has a JDBC driver, you can use
JDBI with it.

JDBI's API comes in two flavors:

- The Core API provides a fluent, imperative interface.

[source,java,indent=0]
-------------------------------------------
include::{exampledir}/IntroductionTest.java[tags=core]
-------------------------------------------

- The SQL Object API sits atop Core, and provides a declarative interface.

[source,java,indent=0]
-------------------------------------------
include::{exampledir}/IntroductionTest.java[tags=sqlobject-declaration]
-------------------------------------------

[source,java,indent=0]
-------------------------------------------
include::{exampledir}/IntroductionTest.java[tags=sqlobject-usage]
-------------------------------------------

JDBI is easy to include in your Java project - with an
link:https://groups.google.com/group/jdbi[Apache 2.0] license,
few external dependencies, and JARs distributed through
link:http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.jdbi%22[Maven Central],
you can just include the relevant artifacts in your POM:

[source,xml,subs="attributes,specialchars"]
-------------------------------------------
<dependency>
  <groupId>org.jdbi</groupId>
  <artifactId>jdbi3</artifactId>
  <version>{project_version}</version>
</dependency>

<dependency>
  <groupId>org.jdbi</groupId>
  <artifactId>jdbi3-sqlobject</artifactId>
  <version>{project_version}</version>
</dependency>
-------------------------------------------

JDBI has a flexible plugin architecture which makes it easy to fold in support
for your favorite libraries (Guava, JodaTime, Spring) or database vendor (Oracle,
Postgres).

JDBI is not an ORM. Bring your own SQL.

Unlike an ORM, JDBI does not pretend to seamlessly convert your Java
object model into the relational model -- instead, it provides easy mapping
between SQL _you_ write and simple tabular data structures.

NOTE: JDBI 3 is currently in beta. While we are reasonably confident in its
quality, we recommend thoroughly testing your code with JDBI 3 before using it in
a production environment. http://www.jdbi.org[jdbi2] is still the stable release.
