http://kotlinlang.org/[Kotlin] support is provided by *jdbi3-kotlin* and *jdbi3-kotlin-sqlobject* modules.


=== ResultSet mapping

The *jdbi3-kotlin* plugin adds ResultSet mapping to Kotlin data classes. It supports data classes where all
fields are present in the constructor as well as classes with writable properties. Any fields not present in the
constructor will be set after the constructor call. The mapper supports nullable types. It also uses default
parameter values in the constructor if the parameter type is not nullable and the value absent in the result set.

If you load all DBI plugins via
`Jdbi.installPlugins()` this plugin will be discovered and registered automatically.
Otherwise, you can attach it using `Jdbi.installPlugin(KotlinPlugin())`.

An example from the test class:

[source,kotlin,indent=0]
-------------------------------------------
include::{exampledir}/KotlinPluginTest.kt[tags=dataClass;testQuery]
-------------------------------------------


There are two extensions to help:

* `<reified T : Any>ResultBearing.mapTo()`
* `<T : Any>ResultIterable<T>.useSequence(block: (Sequence<T>) -> Unit)`

Allowing code like:

[source,kotlin]
----
val qry = handle.createQuery("select id, name from something where id = :id")
val things = qry.bind("id", brian.id).mapTo<Thing>.list()
----

and for using a Sequence that is auto closed:

[source,kotlin]
----
qryAll.mapTo<Thing>.useSequence {
    it.forEach(::println)
}
----



=== SqlObject

The *jdbi3-kotlin-sqlobject* plugin adds automatic parameter binding by name for Kotlin methods in SqlObjects as well as support
for Kotlin default methods.

Parameter binding supports individual primitive types as well as Kotlin or JavaBean style objects as a parameter
(referenced in binding as `:paramName.propertyName`).  No annotations are needed.

If you load all DBI plugins via
`Jdbi.installPlugins()` this plugin will be discovered and registered automatically.
Otherwise, you can attach the plugin via:  `Jdbi.installPlugin(KotlinSqlObjectPlugin())`.

An example from the test class:

[source,kotlin,indent=0]
-------------------------------------------
include::{exampledir}/KotlinPluginTest.kt[tags=sqlObject;setUp;testDao]
-------------------------------------------
