= SqlObject

The Fluent API is very nice to use for full control over
the evaluation of your statements, but sometimes a simpler
declarative approach makes for terse and elegant code.

With *SqlObject*, you write an interface with annotated
methods.  *jdbi* then synthesizes an implementation.

[source,java,indent=0]
-------------------------------------------
include::SqlObjectTest.java[tags=defn]
-------------------------------------------

Given a type *Something* that has *int id* and *String name* 
properties, we define an interface, *SomethingDao*, that
provides simple create and read operations for
a table.

Annotations at the class and method level control
the binding of arguments and mapping to results.
For example, `@RegisterRowMapper` mirrors 
`Handle.registerRowMapper`.

You produce results as single instances
or container types like `Optional` or `List`,
same as `Query.mapTo`.

[source,java,indent=0]
-------------------------------------------
include::SqlObjectTest.java[tags=find-by-id]
-------------------------------------------

There are also `@SqlBatch` and `@SqlCall` annotations.
Check out the Javadoc for more information.
