=== Jdbi

The `Jdbi` object is basically a fancy wrapper around a
`javax.sql.DataSource`. Typically an application will create one
shared `Jdbi` instance application-wide, and set up shared
configuration there.

For now let's just use the out-of-the-box configuration: 

[source,java,indent=0]
-------------------------------------------
include::{exampledir}/FiveMinuteTourTest.java[tags=createJdbi]
-------------------------------------------

=== Handles

The `Handle` is likewise a wrapper around a
`java.sql.Connection`. Care must be taken to close handles
when you are done with them, or else your app will leak database
connections.

You can call `Jdbi.open()` to get a `Handle` instance, but most
of the time you should just use the `Jdbi.useHandle` or
`Jdbi.withHandle` callback methods, which ensure that the handle
is cleaned up, and the connection released before returning to
the caller. Use `withHandle` when your database action returns a
result, or `useHandle` if no result is returned.

[source,java,indent=0]
-------------------------------------------
include::{exampledir}/FiveMinuteTourTest.java[tags=useHandle]
-------------------------------------------

If you do use `Jdbi.open()`, we recommend doing so in a
try-with-resources block for safety.

[source,java,indent=0]
-------------------------------------------------
include::{exampledir}/FiveMinuteTourTest.java[tags=openHandle]
-------------------------------------------------

=== Row Mappers

By default, queries map each row in the result set into a
`Map<String, Object>` which maps the column name to the column
value. You can override this to map to arbitrary row types
using `Query.map(RowMapper<T>)`:

[source,java,indent=0]
---------------------------------------------------------
include::{exampledir}/FiveMinuteTourTest.java[tags=defineCustomMapper]

include::{exampledir}/FiveMinuteTourTest.java[tags=useCustomMapper]
---------------------------------------------------------

Registering a `RowMapper` with the `Handle` or the `Jdbi` (before
the handle is created) allows you to map to the data type
without having to specify the mapper type everywhere:

[source,java,indent=0]
-----------------------------------------------------------
include::{exampledir}/FiveMinuteTourTest.java[tags=registerCustomMapper]
-----------------------------------------------------------

=== Named Parameters

Out of the box, any time you use a colon-prefixed token like
`:name` in a SQL statement, *jdbi* replaces it with the value
you bind to that name:

[source,java,indent=0]
------------------------------------------------------
include::{exampledir}/FiveMinuteTourTest.java[tags=namedParameters]
------------------------------------------------------
