= Transactions

*jdbi* provides full support for JDBC transactions.

== Transactions in the Fluent API

*Handle* objects provide two ways to open a transaction -- *inTransaction* allows
you to return a result, and *useTransaction* has no return value.

Both optionally allow you to specify the transaction isolation level.

[source,java,indent=0]
-------------------------------------------
include::TransactionTest.java[tags=simpleTransaction]
-------------------------------------------

Here, we (probably unnecessarily) guard a simple _SELECT_ statement with a
transaction.

== Transactions in SqlObject API

Similarly, you may declare transactions with SqlObject annotations:

[source,java,indent=0]
-------------------------------------------
include::TransactionTest.java[tags=sqlObjectTransaction]
-------------------------------------------

SQL methods with a `@Transaction` annotation may optionally specify a transaction isolation level:

[source,java,indent=0]
-------------------------------------------
include::TransactionTest.java[tags=sqlObjectTransactionIsolation]
-------------------------------------------

If a `@Transaction` method calls another `@Transaction` method, they must specify the same isolation level, or the
inner method must not specify anything, in which case the isolation level of the outer method is used.

[source,java,indent=0]
-------------------------------------------
include::TransactionTest.java[tags=sqlObjectNestedTransaction]
-------------------------------------------

== Serializable Transactions

For more advanced queries, sometimes serializable transactions are required.
*jdbi* includes a transaction runner that is able to retry transactions that
abort due to serialization failures.  It is important that your transaction
does not have side effects as it may be executed multiple times.

[source,java,indent=0]
-------------------------------------------
include::TransactionTest.java[tags=serializable]
-------------------------------------------

The above test is designed to run two transactions in lock step.
Each attempts to read the sum of all rows in the table, and then
insert a new row with that sum.  We seed the table with the values
10 and 20.

Without serializable isolation, each transaction reads 10 and 20, and
then returns 30.  The end result is 30 + 30 = 60, which does not
correspond to any serial execution of the transactions!

With serializable isolation, one of the two transactions is forced
to abort and retry.  On the second go around, it calculates 10 + 20 + 30 = 60.
Adding to 30 from the other, we get 30 + 60 = 90 and the assertion succeeds.
