package org.skife.jdbi.v2;

import org.junit.Assert;
import org.junit.Test;
import org.skife.jdbi.v2.util.IntegerMapper;

import java.util.Arrays;
import java.util.List;

public class TestPreparedBatchGenerateKeys {

    @Test
    public void testBatchInsertWithKeyGeneration() throws Exception {

        DBI dbi = new DBI("jdbc:hsqldb:mem:jdbi-batch-keys-test", "sa", "");

        Handle h = dbi.open();

        h.execute("create table something (id integer not null generated by default as identity (start with 10000), name varchar(50) )");

        PreparedBatch batch = h.prepareBatch("insert into something (name) values (?)");
        batch.add("Brian");
        batch.add("Thom");
        List<Integer> ids = batch.executeAndGenerateKeys(IntegerMapper.FIRST).list();
        Assert.assertEquals(Arrays.asList(10000, 10001), ids);

        List<Something> somethings = h.createQuery("select id, name from something")
                .map(Something.class)
                .list();
        h.close();

        Assert.assertEquals(Arrays.asList(new Something(10000, "Brian"), new Something(10001, "Thom")), somethings);
    }
}
