/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jdbi.v3.core;

import static org.jdbi.v3.core.ResultProducers.returningGeneratedKeys;
import static org.jdbi.v3.core.ResultProducers.returningUpdateCount;

import java.sql.SQLException;
import java.sql.Statement;
import java.util.Collections;
import java.util.Map;

import org.jdbi.v3.core.exception.UnableToProduceResultException;
import org.jdbi.v3.core.mapper.ColumnMapper;
import org.jdbi.v3.core.mapper.RowMapper;
import org.jdbi.v3.core.statement.StatementBuilder;
import org.jdbi.v3.core.util.GenericType;

/**
 * Used for INSERT, UPDATE, and DELETE statements
 */
public class Update extends SqlStatement<Update> implements ResultBearing
{
    Update(ConfigRegistry config,
           Handle handle,
           StatementBuilder statementBuilder,
           String sql,
           StatementContext ctx)
    {
        super(config, new Binding(), handle, statementBuilder, sql, ctx, Collections.emptyList());
    }

    /**
     * Execute the statement
     * @return the number of rows modified
     */
    public int execute()
    {
        try {
            return execute(returningUpdateCount());
        }
        finally {
            close();
        }
    }

    @Override
    public <R> R execute(ResultProducer<R> producer) {
        try {
            return producer.produce(this::internalExecute, getContext());
        }
        catch (SQLException e) {
            throw new UnableToProduceResultException("Could not produce statement result", e, getContext());
        }
    }

    /**
     * Execute the statement and returns any auto-generated keys. This requires the JDBC driver to support
     * the {@link Statement#getGeneratedKeys()} method.
     * @param mapper the mapper to generate the resulting key object
     * @param columnName name of the column that generates the key
     * @param <T> the type of keys generated by the update
     * @return the generated key or null if none was returned
     */
    public <T> ResultIterable<T> executeAndReturnGeneratedKeys(RowMapper<T> mapper, String columnName)
    {
        return execute(returningGeneratedKeys(columnName)).map(mapper);
    }

    public <T> ResultIterable<T> executeAndReturnGeneratedKeys(RowMapper<T> mapper) {
        return execute(returningGeneratedKeys()).map(mapper);
    }

    public <T> ResultIterable<T> executeAndReturnGeneratedKeys(ColumnMapper<T> mapper) {
        return execute(returningGeneratedKeys()).map(mapper);
    }

    public <T> ResultIterable<T> executeAndReturnGeneratedKeys(Class<T> generatedKeyType) {
        return execute(returningGeneratedKeys()).mapTo(generatedKeyType);
    }

    public <T> ResultIterable<T> executeAndReturnGeneratedKeys(GenericType<T> generatedKeyType) {
        return execute(returningGeneratedKeys()).mapTo(generatedKeyType);
    }

    public ResultIterable<Map<String, Object>> executeAndReturnGeneratedKeys()
    {
        return execute(returningGeneratedKeys()).mapToMap();
    }
}
